### ISSUE TITLE
OrganismBoard should also keep track of the number of points scored

### ISSUE THREAD

**Issue by ggsun** [prismofeverything/organism#1]
The `OrganismBoard` class should also be able to keep track of the number of points scored by each player so far. Ultimately we should be able to determine who won the game by just looking at an instance of this class.

**Comment by ggsun** [comment]
And I don't think the code actually resolves conflicts yet? I can start working on this if you want!

**Comment by prismofeverything** [comment]
@ggsun Hey man, go for it if you want! I can get to it when I'm back otherwise, but feel free to work on the project.
