### ISSUE TITLE
[feature] favicon activity indicator

### ISSUE THREAD

**Issue by creatureface** [prismofeverything/organism#48]
in lieu of any type of notification system, one idea to consider:

a little indicator in the favicon on your browser tab to denote either when it's your turn, or when there has been new activity (someone in your game took their turn)

i've usually seen this as a little red dot on linkedin or microsoft outlook online (blerg, not a good source inspiration, i know, ha):

![Screen Shot 2021-04-13 at 5 28 53 PM](https://user-images.githubusercontent.com/4175912/114637256-ba936900-9c7d-11eb-8f03-b741a5f622a5.png)

**Comment by prismofeverything** [comment]
Awesome idea! Not as intrusive as notifications, but still a reminder (as long as you keep the tab open). I'll add it, thank you.

**Comment by prismofeverything** [comment]
This is complete! in the next update
