### ISSUE TITLE
Keep individual moves private until you submit your turn

### ISSUE THREAD

**Issue by merzee** [prismofeverything/organism#51]
Having the game publicly show every process means those who think through their turn for a while will have all their possible moves seen, which can give an advantage to those watching. Maybe have each move play out in a process for other players only after confirming your turn?

**Comment by prismofeverything** [comment]
It's a good question! I like the immediacy of being able to see what other people are doing, especially if people are playing asynchronously, but I can see your point. Maybe it's an option during game creation time.
